[versions]
junit-jupiter = "6.0.1"
vertx         = "5.0.0"
webauthn4j    = "0.28.2.RELEASE"
slf4j         = "2.0.17"
logback       = "1.5.18"

[libraries]
junit-jupiter   = { module = "org.junit.jupiter:junit-jupiter",    version.ref = "junit-jupiter" }
vertx-web       = { module = "io.vertx:vertx-web",                 version.ref = "vertx" }
webauthn4j-core = { module = "com.webauthn4j:webauthn4j-core",     version.ref = "webauthn4j" }
slf4j-api       = { module = "org.slf4j:slf4j-api",                version.ref = "slf4j" }
logback-classic = { module = "ch.qos.logback:logback-classic",     version.ref = "logback" }
